from generator import generate_table

field_config = {
    'di_Stichtag': ['01.02.2025'],
    'di_ImportDatum': ['04.02.2025'],
    'di_Schuljahr': ['2024/2025'],
    'di_DienststellenNr': [
        3417, 3418, 3419, 3420, 3425, 3426, 3427, 3429, 3430, 3431,
        3432, 3433, 3435, 3436, 3437, 3439, 3440, 3445, 3448, 3451,
        3452, 3453, 3454, 3457, 3464, 3626, 3627, 3628, 3629, 3630,
        3631, 3632, 3633, 3636, 3638, 3639, 3641, 3642, 3643, 3644
    ],
    'di_Standort': [0, 1],
    'di_IstSchule': [0, 1],
    'di_Name': [
        'Limesschule Altenstadt',
        'Janusz-Korczak-Schule',
        'Grundschule Lindheim',
        'Karoline-von-Günderrode-Schule',
        'Stadtschule Büdingen',
        'Eichbaumschule',
        'Schule am Dohlberg',
        'Grundschule Wolf',
        'Georg-August-Zinn-Schule',
        'Düdelsheim',
        'Kurt-Moosdorf-Schule',
        'Grundschule Eichelsdorf',
        'Keltenbergschule',
        'Schule am Niedertor',
        'Erlenbachschule',
        'Seementalschule',
        'Hugo-Buderus-Schule',
        'Herzbergschule',
        'Alteburgschule',
        'Grundschule Ulfa',
        'Grundschule Ober-Widdersheim',
        'Hohebergschule Ober-Lais',
        'Grundschule Wallernhausen',
        'Josef-Moufang-Schule',
        'Maria-Sibylla-Merian-Schule',
        'Ortenberg',
        'Laisbachschule',
        'Solgrabenschule',
        'Stadtschule an der Wilhelmskirche',
        'Wettertalschule',
        'Ernst-Reuter-Schule',
        'Regenbogenschule'
    ],
    'di_NamensZusatz': [''],
    'di_Schultyp': [
        'KGS', 'G', 'HR', 'MSS', 'HRF', 'IGS', 'GHR', 'GHRF', 'GF',
        'LER', 'SOFS', 'GYM', 'GOS', 'BS', 'AR', 'AGYM', 'H', 'GH',
        'MSSG', 'GHF', 'GR', 'SO', 'R', 'GYMM', 'KO', 'KMSS'
    ],
    'di_Schultyp_lang': [
        'Schulformbezogene (kooperative) Gesamtschule',
        'Grundschule',
        'Haupt- und Realschule',
        'Mittelstufenschule',
        'Haupt- und Realschule mit Förderstufe',
        'Schulformübergreifende (integrierte) Gesamtschule',
        'Grund-, Haupt- und Realschule',
        'Grund-, Haupt- und Realschule mit Förderstufe',
        'Grundschule mit Förderstufe',
        'Schule mit dem Förderschwerpunkt Lernen',
        'Sonstige Förderschule',
        'Gymnasium (Mittel- und Oberstufe)',
        'Gymnasiale Oberstufenschule',
        'Berufliche Schule',
        'Abendrealschule',
        'Abendgymnasium',
        'Hauptschule',
        'Grund- und Hauptschule',
        'Mittelstufenschule mit Grundschule',
        'Grund- und Hauptschule mit Förderstufe',
        'Grund- und Realschule',
        'Sonderschule',
        'Realschule',
        'Gymnasium (Mittelstufe)',
        'Kolleg',
        'Kooperative Gesamtschule mit Mittelstufenschule'
    ],
    'di_SchultypGruppe': [
        'KGS', 'GHR', 'IGS', 'FS', 'GYM', 'BS', 'SFE'
    ],
    'di_SchultypGruppe_lang': [
        'Schulformbezogene (kooperative) Gesamtschulen',
        'Grund-Haupt-Realschulen',
        'Schulformübergreifende (integrierte) Gesamtschulen',
        'Förderschulen',
        'Gymnasien',
        'Berufliche Schulen',
        'Schulen für Erwachsene'
    ],
    'di_Rechtsstellung': [
        'ÖFF', 'PRI', 'LWV', 'BBW', 'STAT', 'ERGG'
    ],
    'di_Rechtsstellung_lang': [
        'Öffentliche Schulen',
        'Private Ersatzschule',
        'Landeswohlfahrtsverbandsschulen',
        'Berufsbildungswerke',
        'Staatliche Technikerschule',
        'Genehmigte private Ergänzungsschule'
    ],
    'di_RechtsstellungGruppe': [
        'öffentlich', 'privat'
    ],
    'di_Schultraeger': [
        'WK', 'SONS', 'LWV', 'KI', 'LH', 'WI', 'F', 'LM', 'GG', 'VB',
        'DADI', 'FDS', 'KSS', 'MRS', 'WM', 'WF', 'SEK', 'FDL', 'HR',
        'KSL', 'MRL'
    ],
    'di_Schultraeger_lang': [
        'Wetteraukreis',
        'Sonstiger Schulträger (Privatschulen)',
        'Landeswohlfahrtsverband',
        'Kirchen/Glaubensgemeinschaften',
        'Land Hessen',
        'Stadt Wiesbaden',
        'Stadt Frankfurt am Main',
        'Landkreis Limburg-Weilburg',
        'Landkreis Groß-Gerau',
        'Vogelsbergkreis',
        'Landkreis Darmstadt-Dieburg',
        'Stadt Fulda',
        'Stadt Kassel',
        'Stadt Marburg',
        'Werra-Meißner-Kreis',
        'Landkreis Waldeck-Frankenberg',
        'Schwalm-Eder-Kreis',
        'Landkreis Fulda',
        'Landkreis Hersfeld-Rotenburg',
        'Landkreis Kassel',
        'Landkreis Marburg-Biedenkopf'
    ],
    'di_SchultraegerGruppe': [''],
    'di_SchultraegerGruppe_lang': [''],
    'di_Schulaufsicht': [
        'HTW', 'GIVB', 'RTWI', 'F', 'FD', 'KS', 'MR', 'HRWM',
        'SEWF', 'OF', 'GGMT', 'BOW', 'LDLM', 'DADI', 'MKK'
    ],
    'di_Schulaufsicht_lang': [
        'SSA für den Hochtaunuskreis und den Wetteraukreis',
        'SSA für den Landkreis Gießen und den Vogelsbergkreis',
        'SSA für den Rheingau-Taunus-Kreis und die Stadt Wiesbaden',
        'SSA für die Stadt Frankfurt am Main',
        'SSA für den Landkreis Fulda',
        'SSA für den Landkreis Kassel und die Stadt Kassel',
        'SSA für den Landkreis Marburg-Biedenkopf',
        'SSA für den Landkreis Hersfeld-Rotenburg und den Werra-Meißner-Kreis',
        'SSA für den Schwalm-Eder-Kreis und den Landkreis Waldeck-Frankenberg',
        'SSA für den Landkreis Offenbach und die Stadt Offenbach am Main',
        'SSA für den Landkreis Groß-Gerau und den Main-Taunus-Kreis'
    ],
    'di_NameStelle': [
        'Limesschule Altenstadt',
        'Janusz-Korczak-Schule',
        'Grundschule Lindheim',
        'Karoline-von-Günderrode-Schule',
        'Stadtschule Büdingen',
        'Aussenstelle Lorbach',
        'Eichbaumschule',
        'Schule am Dohlberg',
        'Grundschule Wolf',
        'Georg-August-Zinn-Schule',
        'Düdelsheim',
        'Kurt-Moosdorf-Schule',
        'Grundsch. Eichelsdorf',
        'Keltenbergschule',
        'Schule am Niedertor',
        'Erlenbachschule',
        'Seemental-Schule',
        'Hugo-Buderus-Schule',
        'Herzbergschule',
        'Alteburgschule',
        'Grundschule Ulfa',
        'Grundschule Ober-Widdersheim',
        'Hoheberg-Schule',
        'Grundsch. Wallernhau',
        'Josef-Moufang-Schule',
        'Maria-Sibylla-Merian-Schule',
        'Laisbachschule',
        'Solgrabenschule',
        'Stadtschule an der Wilhelmskirche',
        'Stadtschule an der Wilhelmkirche',
        'Wettertalschule',
        'Wettertalschule, NSt. Schwalheim',
        'Ernst-Reuter-Schule Bad Vilbel',
        'Regenbogenschule',
        'Saalburgschule Bad Vilbel',
        'John-F.-Kennedy-Schule',
        'Stadtschule Bad Vilbel',
        'Degerfeldschule'
    ],
    'di_Strasse': [
        'Schillerstraße 2',
        'Fritz-Kress-Straße 9',
        'Im Schlag 22',
        'Mittelstraße 57',
        'Brunostraße 8',
        'Am Herrngarten 3',
        'Herrnhuter Straße 40',
        'In der Langewann 3-5',
        'Wasserweg 5',
        'Schulstraße 6',
        'Hauptstraße 61-63',
        'Eichelstrasse 25',
        'Bahnhofstraße 8',
        'Untertorstraße 21',
        'Öchlerweg',
        'Friedhofstraße 1',
        'An der Klostermauer 1',
        'Schulstraße 8',
        'Am Heiligen Kreuz 34',
        'Steinstraße 10',
        'Wydratstraße 56',
        'Unter-Laiser-Straße 7',
        'Kohlstraße 12',
        'Pflanzenländer Weg 4',
        'Oberriedstraße 30',
        'Am Solgraben 6',
        'Mittelstraße 30',
        'Rotdornstraße 21-23',
        'Wettertalstraße 12',
        'Schwalheimer Hauptstraße 61',
        'Pestalozzistraße 6',
        'Beethovenstraße 2-4',
        'Bahnhofstraße 37',
        'Saalburgstraße 84',
        'Frankfurter Straße 85',
        'Aueweg 9',
        'Astrid-Lindgren-Straße 2',
        'Oppershofener Straße 14'
    ],
    'di_PLZ': ['63674', '63065', '61169'],
    'di_Ort': [
        'Altenstadt',
        'Büdingen',
        'Echzell',
        'Nidda',
        'Glauburg',
        'Gedern',
        'Hirzenhain',
        'Kefenrod',
        'Nidda-Wallernhausen',
        'Ortenberg',
        'Ranstadt',
        'Bad Nauheim',
        'Bad Vilbel',
        'Butzbach',
        'Friedberg (Hessen)',
        'Florstadt',
        'Münzenberg',
        'Karben',
        'Niddatal',
        'Wöllstadt',
        'Ober-Mörlen',
        'Reichelsheim (Wetterau)',
        'Rockenberg',
        'Rosbach v. d. Höhe',
        'Rosbach',
        'Wölfersheim',
        'Limeshain',
        'Friedberg',
        'Gießen',
        'Wiesbaden',
        'Frankfurt am Main',
        'Limburg',
        'Groß-Gerau',
        'Alsfeld',
        'Dieburg',
        'Fulda',
        'Kassel',
        'Marburg'
    ],
    'di_Telefon': ['+4900000000', '+4900000001', '+4900000002'],
    'di_Telefon2': ['kein Eintrag'],
    'di_Fax': ['+4900000000', '+4900000001', '+4900000002'],
    'di_URL': ['kein Eintrag'],
    'di_Email': [
        'info@schule.de',
        'kontakt@schule.de',
        'mail@schule.de',
        'schule@web.de',
        'admin@schule.de',
        'post@schule.de',
        'sekretariat@schule.de',
        'kein.eintrag@schule.de',
        'test@schule.de',
        'schule@example.com'
    ],
    'di_OrtsteilKz': [''],
    'di_OrtsteilName': ['kein Eintrag'],
    'di_GemeindeKz': ['09990000001', '09990000002', '09990000002'],
    'di_GemeindeName': [
        'Altenstadt',
        'Büdingen',
        'Echzell',
        'Nidda',
        'Glauburg',
        'Gedern',
        'Hirzenhain',
        'Kefenrod',
        'Nidda-Wallernhausen',
        'Ortenberg',
        'Ranstadt',
        'Bad Nauheim',
        'Bad Vilbel',
        'Butzbach',
        'Friedberg (Hessen)',
        'Florstadt',
        'Münzenberg',
        'Karben',
        'Niddatal',
        'Wöllstadt',
        'Ober-Mörlen',
        'Reichelsheim (Wetterau)',
        'Rockenberg',
        'Rosbach v. d. Höhe',
        'Rosbach',
        'Wölfersheim',
        'Limeshain',
        'Friedberg',
        'Gießen',
        'Wiesbaden',
        'Frankfurt am Main',
        'Limburg',
        'Groß-Gerau',
        'Alsfeld',
        'Dieburg',
        'Fulda',
        'Kassel',
        'Marburg'
    ],
    'di_GemeindeName_kurz': [
       'Altenstadt',
       'Büdingen',
       'Echzell',
       'Nidda',
       'Glauburg',
       'Gedern',
       'Hirzenhain',
       'Kefenrod',
       'Nidda-Wallernhausen',
       'Ortenberg',
       'Ranstadt',
       'Bad Nauheim',
       'Bad Vilbel',
       'Butzbach',
       'Friedberg (Hessen)',
       'Florstadt',
       'Münzenberg',
       'Karben',
       'Niddatal',
       'Wöllstadt',
       'Ober-Mörlen',
       'Reichelsheim (Wetterau)',
       'Rockenberg',
       'Rosbach v. d. Höhe',
       'Rosbach',
       'Wölfersheim',
       'Limeshain',
       'Friedberg',
       'Gießen',
       'Wiesbaden',
       'Frankfurt am Main',
       'Limburg',
       'Groß-Gerau',
       'Alsfeld',
       'Dieburg',
       'Fulda',
       'Kassel',
       'Marburg'
   ],
    'di_LandkreisKz': ['09990000001', '09990000002', '09990000002'],
    'di_LandkreisName': [
        'Wetteraukreis',
        'Gießen',
        'Wiesbaden',
        'Frankfurt am Main, Stadt',
        'Limburg-Weilburg',
        'Groß-Gerau',
        'Vogelsbergkreis',
        'Darmstadt-Dieburg',
        'Fulda',
        'Kassel, Stadt',
        'Marburg-Biedenkopf',
        'Werra-Meißner-Kreis',
        'Waldeck-Frankenberg',
        'Schwalm-Eder-Kreis',
        'Hersfeld-Rotenburg',
        'Kassel',
        'Offenbach am Main, Stadt',
        'Main-Taunus-Kreis',
        'Odenwaldkreis',
        'Hochtaunuskreis',
        'Standort nicht in Katalog',
        'Darmstadt, Stadt',
        'Rheingau-Taunus-Kreis',
        'Main-Kinzig-Kreis',
        'Bergstraße'
    ],
    'di_RegierungsbezirkKz': ['09990000001', '09990000002', '09990000002'],
    'di_RegierungsbezirkName': [
        'Reg.-Bez. Darmstadt',
        'Reg.-Bez. Gießen',
        'Reg.-Bez. Kassel',
        'Standort nicht in Katalog'
    ],
    'di_Planungsregion': [3417, 3418, 3419, 3420, 3425, 3426, 3427, 3429, 3430, 3431],
    'di_Planungsregion_lang': [
        'Altenstadt - Limeshain',
        'Büdingen',
        'Nidda',
        'Ortenberg, Ranstadt, Glauburg',
        'Gedern - Hirzenhain',
        'Bad Nauheim',
        'Bad Vilbel',
        'Butzbach',
        'Friedberg',
        'Karben',
        'Ost',
        'Ohne Planungsregion',
        'F-',
        'Ginnheim/Eschersheim/Dornbusch',
        'Limburg',
        'Groß-Gerau',
        'Alsfeld',
        'Dieburg',
        'Fulda Innenstadt',
        'Fulda Süd-West',
        'Fulda Nord',
        'Waldau/Forstfeld/Wehlhausen',
        'Mitte/Süd/Wehlheiden',
        'Zwehren/Süsterfeld/Helleböhn',
        'Jungfernkopf/Rothenditmold',
        'Nord/Warteberg/Unterneustadt/Wesertor',
        'Harleshausen/Kirchditmold/Wilhelmshöhe',
        'Marburg-Stadt',
        'Eschwege',
        'Sontra',
        'Frankenberg',
        'Korbach',
        'Fritzlar',
        'Homberg',
        'Schwalmstadt',
        'Landkreis Fulda-West'
    ],
    'di_Planungsbereich': [''],
    'di_Planungsbereich_lang': [''],
    'di_AnzahlAktiverStandorte': [0, 1],
    'di_VorhandeneSchulformAngebote': [
        'F, GOS, GYM9, H, R',
        'G',
        'G, GFLX',
        'H, R',
        'MSS',
        'H, MSS',
        'F, H, R',
        'E, G',
        'IGS, PUSA',
        'G, H, R',
        'G, SPR',
        'F, G, H, R',
        'G, IGS',
        'F, G',
        'EMS, GE, LER',
        'EMS, LER',
        'BLI, HÖR, SEH',
        'BFS2, BST, BZBT, BZBV',
        'HÖR',
        'BFS2, BST, BZBV',
        'GE',
        'LER',
        'IGS',
        'F, FG8',
        'G, GYM8',
        'GOS, GYM9',
        'GOS',
        'G, GOS, GYM9',
        'GYM9, H, R',
        'GOS, GYM9, H, R',
        'BBGT, BBGV, BFS1, BFS2, BFSAM, BST, FOS',
        'FOS',
        'BFS2, BFSAM, FOS',
        'BFS2, BFSAM, BST, BZBT, BZBV, FS2, PUSB',
        'BFS2, BGYM, BST, BZBT, BZBV, FOS',
        'BBGV, BFS2, BFSAM, BST, FSS',
        'BFS2, BFSAM, BJKV, BST, BZBT, BZBV'
    ],
    'di_Voraussetzung': ['K', 'OHNE'],
    'di_Voraussetzung_lang': [
        'Koedukativ',
        'Ohne Voraussetzung',
        'kein Eintrag',
        'Nicht koedukativ (Mädchen)'
    ],
    'di_LoeschDatum': ['kein Eintrag', '', '30.07.2007'],
    'di_SchulleiterName': [
        'Neubauer', 'Schwan', 'Vogtmann', 'Kraushaar', 'Heusinger',
        'Brügge', 'Teschner', 'Wittenberg', 'Halbritter', 'Eifler',
        'Rostock', 'Kalden', 'Ostermann', 'Wehrle', 'Schnarre',
        'Blankertz', 'Thalheim', 'Mertzig', 'Plötz', 'Nitschke',
        'Hagemeister', 'Krahmer', 'Opitz', 'Willebrand', 'Tönnies',
        'Knust', 'Kronfeld', 'Bickelhaupt', 'Esser', 'Gessler'
    ],
    'di_SchulleiterVorname': [
        'Ronny', 'Miriam', 'Tobias', 'Isabell', 'Henrik',
        'Dana', 'Malte', 'Theresa', 'Nico', 'Annette',
        'Pascal', 'Lena', 'Julian', 'Romy', 'Felix',
        'Jasmin', 'Benedikt', 'Helene', 'Fabian', 'Verena',
        'Till', 'Janina', 'Stefanie', 'Oliver', 'Nina',
        'Dominik', 'Eva', 'Daniel', 'Marina', 'Levin'
    ],
    'di_SchulleiterTitel': ['kein Eintrag'],
    'di_SchulleiterGeschlecht': ['M', 'W', '-']
}

if __name__ == '__main__':
    generate_table(field_config, num_rows=500, output_file='Schulen.xlsx')
